version: '3'

services:
  cert-kong-proxy:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
      target: dev
    image: cert-kong-proxy
    environment:
      CLIENT_SECRET: secret
      CLIENT_ID: client
      KEYCLOAK_REALM: master
      GATEWAY_URL: http://logger_server:8080
      KEYCLOAK_URL: http://keycloak:8080
      CA_URL: http://ca:8080