name: Tests
on:
  push:
    branches:
      - master
      - dev
    pull_request:
      branches:
      - master
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: docker compose -f deployment/test/docker-compose.yml up 
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: /home/coverage.xml
